name: 'netease-recent-actions'
description: 'This action allows you to generate an svg profile from your NetEase Cloud Music account'
author: 'zonemeen <miqilin18@gmail.com>'

branding:
  icon: 'music'
  color: 'blue'
inputs:
  id:
    description: 'This is your NetEase Cloud Music account id.'
    required: true
  type:
    description: 'Song ranking type, 1 for weekData, 0 for allData'
    required: false
  number:
    description: 'The number of songs'
    required: false

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - shell: bash
      run: |
        cd ${{ github.action_path }}
        pip install -r requirements.txt
        npm i -g pnpm
        pnpm install
        node index.js --id ${{ inputs.id }} --type ${{ inputs.type }} --number ${{ inputs.number }}
        cp 163.svg ${{ github.workspace }}

outputs:
  deployment-status:
    description: 'The status of the deployment that indicates if the run failed or passed. Possible outputs include: success|failed|skipped'
